services:
  student-management:
    build: .
    container_name: student-management-container
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - student-network

  postgres:
    image: postgres:16
    container_name: student-postgres-container
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - student-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  student-network:

volumes:
  postgres-data: