# Server Configuration
server.port=8081


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=apple
spring.datasource.password=


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


# Optional: Format SQL Queries
spring.jpa.properties.hibernate.format_sql=true